-- SQL to create the food_conflicts table in your Supabase project
-- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)

CREATE TABLE IF NOT EXISTS food_conflicts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  medicine_names JSONB NOT NULL DEFAULT '[]'::jsonb,
  selected_foods JSONB NOT NULL DEFAULT '[]'::jsonb,
  conflicts JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE food_conflicts ENABLE ROW LEVEL SECURITY;

-- Allow users to view only their own conflict checks
CREATE POLICY "Users can view their own food conflicts"
  ON food_conflicts FOR SELECT
  USING (auth.uid() = user_id);

-- Allow users to insert their own conflict checks
CREATE POLICY "Users can insert their own food conflicts"
  ON food_conflicts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Index for quick lookups by user_id
CREATE INDEX IF NOT EXISTS idx_food_conflicts_user_id ON food_conflicts(user_id);

-- Index for ordering by creation time
CREATE INDEX IF NOT EXISTS idx_food_conflicts_created_at ON food_conflicts(created_at DESC);